### DISCUSSION TITLE
Can figures in Jupyter book be numbered by section, not for the entire book?

### DISCUSSION THREAD

**Discussion by fmaussion** [executablebooks/meta#1032] [Q&A]
Sorry if I missed that in the documentation https://jupyterbook.org/en/stable/content/figures.html

I have a book with 60+ figures and the numbering is a bit unclear because of that.

**Comment by kthyng** [comment]
Me too — I have hundreds of figures so far!

**Comment by psychemedia** [comment]
For numbering figures, I use the following settings in `_config.py` to force section level figure numbering and referencing:

```yaml
sphinx:
 ...
  config:
    ...
    numfig: true
    numfig_format: {'figure':'Figure %s'}
    numfig_secnum_depth: 1 #eg 0:1 1:2.1 2:3.2.1
    ...
```
