### DISCUSSION TITLE
Light Mode Only Possible?

### DISCUSSION THREAD

**Discussion by canyon289** [executablebooks/meta#1081] [General] [answered]
Is there a way to only have light mode, or at least default to light mode? I've read through the issue tickets and modified by config accordingly but it does not seem to take.

Thanks in advance for any help

https://github.com/executablebooks/jupyter-book/issues/1430
https://github.com/canyon289/GenAiGuidebook/blob/main/genaiguidebook/_config.yml#L36-L39

https://ravinkumar.com/GenAiGuidebook/book_intro.html

**Comment by agahkarakuzu** [comment, marked as answer]
@canyon289 can you try the following in the `_config.yml`:


```yaml
sphinx:
  recursive_update: true
  config:
    html_context:
      default_mode: dark
```

instead of

```yaml
sphinx:
  html_context:
    default_mode: light
```

You may need to flush the cache on your browser to see the effect.  I am sure the following works, but not sure about `html_context`:

```
    html_theme_options:
      logo:
        image_light: "some-logo-light.png"
        image_dark: "some-logo-dark.png"
```

I used jupyter-book `0.15.1`
