### DISCUSSION TITLE
Logo for site action

### DISCUSSION THREAD

**Discussion by corentinmorice1** [executablebooks/meta#1115] [Q&A]
I have a website with an action (a link at the top of the webpage, like the "Learn More" button in the template). I would like to replace the text on this action with a logo. Is that possible? I tried
```
actions:
    - title: My Link
      url: https://www.my-link.com
      logo: my-logo.jpg
```
with no success.
