### DISCUSSION TITLE
How to include the root in the toc?

### DISCUSSION THREAD

**Discussion by ajfriend** [executablebooks/meta#1158] [Q&A]
I have a `_toc.yml` like:

```yaml
format: jb-book
root: intro
parts:
- caption: h3-py
  chapters:
  - file: api_quick
  - file: api_verbose
  - file: polygon_tutorial
  - file: api_comparison
```

But I'd like to explicitly include `intro` in the table of contents on the side. How do I do that? When I try to include it, I get an error about `intro` being included twice.

Looking through the gallery, [this project](https://pyhf.github.io/pyhf-tutorial/) has a similar `_toc.yml`, but they have their root appearing in the site's table of contents. I can't see what they're doing differently to enable that. Any help would be appreciated!

**Comment by ajfriend** [comment]
I've tried configs like:

```yaml
format: jb-book
root: intro
parts:
- caption: Introduction
  chapters:
  - file: intro
- caption: h3-py
  chapters:
  - file: api_quick
  - file: api_verbose
  - file: polygon_tutorial
  - file: api_comparison
```

but this results in the error: `The Table of Contents file is malformed: document file used multiple times: 'intro'`

On the other hand, it seems like https://pyhf.github.io/pyhf-tutorial/ achieves what I'd like to do without having to list their introduction file twice in `_toc.yaml`.
