### DISCUSSION TITLE
Is it possible to have a different logo image for light and dark mode?

### DISCUSSION THREAD

**Discussion by snowch** [executablebooks/meta#1228] [Q&A] [answered]
My logo looks bad in dark mode, I was wondering if there is a way to swap it.  I.e. have two logos, one for each mode.

It looks like sphinx book supports this via [html_theme_options](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/branding.html#different-logos-for-light-and-dark-mode)

```python
# Assuming your `conf.py` has a sibling folder called `_static` with these files
html_theme_options = {
   "logo": {
      "image_light": "_static/logo-light.png",
      "image_dark": "_static/logo-dark.png",
   }
}
```

So, I'm hoping this should be possible with jupyterbook?

**Comment by snowch** [comment, marked as answer]
It was possible to set these values in the _config.yml:

```yml
sphinx:
  config:
    html_theme_options:
      logo:
        image_light: logo-light.png
        image_dark: logo-dark.png
```
