### DISCUSSION TITLE
dropdown proof in jupyterbook

### DISCUSSION THREAD

**Discussion by MPenaR** [executablebooks/meta#1230] [Q&A]
I'm trying to write a book where the proofs do not distract from the rest of the content. As so, I am writting every proposition and proof as: 

```{prf:proposition}
$$
\frac{1}{a+b} = \frac{1}{a} + \frac{1}{b}
$$
```

```{prf:proof}
:class: dropdown

its easy to check its equality for 

$$
a=b=0
$$ 

and for 

$$
a=b=\infty
$$ 

The veracity for any other value of $a$ and $b$ can be proved by interpolation. This is left to the reader.
```

However, when I build the book the proof is shown without the option to hide it. (That does not happen if I simply use

```{dropdown} Proof:
...
```

That is, in this case everything works fine. My _config.yml looks like this:

```yaml
sphinx:
  extra_extensions          : # A list of extra extensions to load by Sphinx (added to those already used by JB).
    - sphinx_proof
    - sphinx_togglebutton    
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  recursive_update          : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config                    :  
    language: es # key-value pairs to directly over-ride the Sphinx configuration
```

I added the "sphinx_togglebutton" thinking that would fix it, but it didn't.
