### DISCUSSION TITLE
Centered tables from .ipynb

### DISCUSSION THREAD

**Discussion by MantiMantilla** [executablebooks/meta#175] [Q&A] [answered]
This might seem silly, but I'm well invested in making this work and there's no turning back now.
I'd like the markdown tables from my .ipynb files to be centered on the jupyter-book static site.
I've tried:
- swapping them for MathJax arrays but that lacks some flexibility,
- writing a MyStyle.css in the `_static/` directory with this style: `table { margin-left: auto; margin-right: auto;}` (does nothing),
- including `%%HTML` cell in my .ipynb files that would align any subsequent content (couldn't get the HTML cells to work),
- adding tags to the cells' metadata.

I'm particularly fond of the .css approach, but I can't find much documentation on what would give me the desired result.
Mind you, the .css file also includes styling for paragraphs to justify all text (`p { text-align:justify; }`). 
Any help is welcome! Thank you in advance.

**Comment by MantiMantilla** [comment, marked as answer]
Turns out this CAN be done. It's just that the .css styling rules weren't being given enough priority. I added the `!important` tag to my rules and that fixed it. In case anybody comes across this, later on, the following is my .css code to justify or center-align most book contents.
```css
p {
  text-align: justify;
}
table {
    display: table !important;
    margin-left: auto !important;
    margin-right: auto !important;
}
.table {
    width: auto !important;
}
```
