### DISCUSSION TITLE
Override the kernel

### DISCUSSION THREAD

**Discussion by henryiii** [executablebooks/meta#222] [Q&A]
How to I override the kernel? I'm using `nb_conda_kernels` to access my conda environments as kernels, and jupyterbook doesn't seem to be triggering that mechanism, causing it to simply report it can't find the kernel. I've tried to override it:

```yaml
sphinx:
  config:
    nbsphinx_kernel_name: python3
```

But it doesn't seem to be picking it up, it's still trying the kernel in the notebooks.

Also, related, any plans for a conda-forge package?
