### DISCUSSION TITLE
can't seem to use pure markdown notebooks as input ~~was: trouble with executing ijavascript-backed notebooks in jupyter-book~~

### DISCUSSION THREAD

**Discussion by parmentelat** [executablebooks/meta#272] [Q&A]
Hi

I am trying to use jupyter-book on a project where all notebooks run [the ijavascript kernel](https://github.com/n-riesco/ijavascript)

all notebooks are stored as myst

book production works well overall, except that notebooks **won't gets executed**
I tried various combinations of `execute_notebooks`, to no avail
for the sake of checking the config, I added a plain Python3 notebook, and it got executed all right

is there anything specific to be configured to get non-Python kernels to execute as expected ?

if that was expected to work out of the box, I can go ahead and file an issue in the jupyter-book repo

and btw: thanks for jupyter-book; I had given the tool a try a year or so ago, had been struggling a lot at the time, but it looks like plenty of improvements have been made in the meanwhile, and the doc itself is much clearer for starters; so congrats :)

**Comment by parmentelat** [comment]
as a follow-up, it took me a while to figure that my inputs were actually plain markdown notebooks, not myst, and that's why jb refused to execute them; nothing to do with the kernel then

**Reply by choldgraf** [reply]
Ahh gotcha, so has this been resolved then? You’re correct that non python notebooks should be treated no differently from any other

**Comment by parmentelat** [comment]
to clarify: it seems like my issue had nothing to do with ijavascript at all, or with the kernel not being Python

what happened is: it looks like jb assumes that a file ending in `.md` is either a myst notebook, or not a notebook

turns out I had **.md files** that were notebooks allright, but **not myst** - there were what jupytext calls regular markdown, I mean starting with this:

```
---
jupyter:
  jupytext:
    text_representation:
      extension: .md
      format_name: markdown
      format_version: '1.2'
      jupytext_version: 1.9.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---
```

when feeding jb with this file as part of `_toc.yml`, I was getting the contents allright but with **no cell executed**

turns out the input file was silently considered as not a notebook, and I essentially had to run myst-nb in debugging mode to realize that; my feeling is this could be made a more serious message (now I may have missed some option to get more helpful messages about that ?) 

---

as an aside, at some point I tried to add this in the config, which is something that worked for me in another project where I had only `py:percent` input notebooks; 

```
sphinx:
  config:
    nb_custom_formats:
      .md:
        - jupytext.reads
        - fmt: markdown
```

however with this in place I am getting this:

```
Extension error:
source_suffix '.md' is already registered
```

so my take away message at this point is, I can't seem to use pure markdown notebooks as an input at all; or what am I missing ?
