### DISCUSSION TITLE
How to suppress the various warnings at build time

### DISCUSSION THREAD

**Discussion by DKilkenny** [executablebooks/meta#326] [Q&A]
Hello, 

I am currently buildings some docs that don't all need to be in the `_toc.yml` and I'm trying to figure out how to suppress all the different warnings such as:
- `WARNING: document isn't included in any toctree`
- `Document or section may not begin with a transition`
- `WARNING: Found a content page that is not in _toc.yml`
- `WARNING: Unexpected section title.`

These are warnings that I'm ok with ignoring and just want to hide them so I can find other issues easier. I have tried adding to the `suppress_warnings` but to no avail.
```
sphinx:
  config:
    suppress_warnings:
      - myst.domains
      - nbsphinx
      - autodoc
      - autodoc.import_object
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
```
