### DISCUSSION TITLE
How to include rst-files which themselves include other rst-files?

### DISCUSSION THREAD

**Discussion by nunupeke** [executablebooks/meta#332] [Q&A]
I have a jupyter book consisting of tutorials (written in jupyter notebooks) and an api reference (rst-file). My `_toc.yml` looks like this

```yml
- file: index
  sections:
    - file: tutorial_1
    - file: tutorial_2
    - file: api_ref
```

The api reference rst-file itself includes other rst-files that are generated using the sphinx autosummary extension. When building my book, I get the warning "Found a content page that is not in _toc.yml" for every file that is included by `api_ref.rst`. Is this intended behaviour (i.e. am I doing something wrong)? Or can / should I silence these warnings?

In the final output, all rst-files are included Ok.
