### DISCUSSION TITLE
Add logo to pdf cover

### DISCUSSION THREAD

**Discussion by ghost** [executablebooks/meta#351] [Q&A] [answered]
I'd like to add my logo to the cover of the generated pdf (--pdflatex), is this possible?
I have the logo defined in _config.yml, it shows when generating HTML, but in the pdf not.

**Comment by choldgraf** [comment, marked as answer]
@mmcky maybe this is in the plan for jupyterbook-latex?

**Reply by mmcky** [reply]
this is a nice idea. I'll open a tracking feature request to include it on the `pdf`

**Reply by mmcky** [reply]
https://github.com/executablebooks/jupyterbook-latex/issues/58

**Reply by rossbar** [reply]
FWIW I've used the [`latex_logo`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_logo) config value for this.

**Reply by mmcky** [reply]
thanks @rossbar -- was just taking a look at `sphinx` docs to see if there was a special `latex` key for the `logo`. I will update the `jupyterbook-latex` issue to add an alternative to improve the docs.

**Reply by hygorxaraujo** [reply]
Where should I include the `latex_logo` in _config.yml?
```yaml
title: NXT - Project 2
author: JoinAnalytics
latex_logo: logo.png <-- Here?

latex:
  latex_engine: "xelatex"
  latex_logo: logo.png <-- Or here?
  use_jupyterbook_latex: false
  latex_documents:
    targetname: report.tex
```
I tried both but it didn't work.

Thank you for all the replies!

**Reply by rossbar** [reply]
If you're using the jupyter-book config I think it would look something like:

```yaml
sphinx:
  config:
    latex_logo: my_title_img.png
```
