### DISCUSSION TITLE
Blank pages in generated PDF

### DISCUSSION THREAD

**Discussion by ghost** [executablebooks/meta#352] [Q&A] [answered]
I'm using jupyter-book to generate a PDF with --pdflatex.
The generated PDF has a blank page after the cover and another after the index.
Is it possible to change configuration to not generate these blank pages?

**Comment by ghost** [comment, marked as answer]
Just found the answer, based on [this stackoverflow answer](https://stackoverflow.com/a/5741112/2550932).
In the _config.yml add the extraclassoptions:
```yaml
sphinx:
  config:
    latex_logo: logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
```
