### DISCUSSION TITLE
_toc.yml parts and chapters

### DISCUSSION THREAD

**Discussion by rillonline** [executablebooks/meta#440] [Q&A] [answered]
I have just started to use Jupyterbook on Debian Buster. I am unable to build a table of contents using parts. I have read the documentation here.
https://jupyterbook.org/customize/toc.html#structure-book
If I am understanding this correctly, "parts:" is is used only once in
the _toc.yml file. - caption: repeats to give the title of each part
and chapters: indicates a list of files for each chapter will follow
with the format: - file: filename. But this isn't working.
I can create a book with chapters but not parts and chapters.
I am usingJupyter-Book v0.11.2and Sphinx v3.5.4 which is what pip
installed on my system.
I am a writer not a python coder so I can tell you little about my python environment except to say its 3.7..
I am probably missing something very simple but I would like to get this working.

**Comment by choldgraf** [comment]
It's helpful if you post an example of the TOC that doesn't work, can you do so?

**Comment by rillonline** [comment]
Of course.
```
# Table of contents
# Learn more at https://jupyterbook.org/customize/toc.html

format: jb-book
root: index
parts:
- caption: Part 1
chapters:
- file: note-to-the-reader
- caption: Part 2
chapters:
- file: b01file01
- file: b01file02
- file: b01file03
- file: b01file04
- caption: Part 3
chapters:
- file: thoughts-on-the-first-adventure
- file: glossary
```
Everything is left justified.

**Reply by choldgraf** [reply]
thanks - what kind of error message are you getting?

**Reply by chrisjsewell** [reply]
> Everything is left justified.

Heya, I'm not quite sure why you chose to left justify everything, but yeh it should look like this:

```yaml
format: jb-book
root: index
parts:
- caption: Part 1
  chapters:
  - file: note-to-the-reader
- caption: Part 2
  chapters:
  - file: b01file01
  - file: b01file02
  - file: b01file03
  - file: b01file04
- caption: Part 3
  chapters:
  - file: thoughts-on-the-first-adventure
  - file: glossary
```
