### DISCUSSION TITLE
Make a custom 404 page for Jupyter Book

### DISCUSSION THREAD

**Discussion by melaniewalsh** [executablebooks/meta#476] [Show and tell]
Last year, I wanted to create a custom 404 page for my Jupyter Book that would maintain its styling and table of contents. This can be tricky to do with Sphinx, but there's a great Sphinx extension called [`sphinx-notfound-page`](https://github.com/readthedocs/sphinx-notfound-page) that makes it possible.

However, as I posted in [this issue](https://github.com/executablebooks/sphinx-book-theme/issues/227), I was having some trouble getting the extension to work with my Jupyter Book. But I finally found a solution this week! Here's an [example of the 404 page](https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/not-a-real-link):
![Screen Shot 2021-09-01 at 8 03 58 AM](https://user-images.githubusercontent.com/20325102/131695709-070ec3e8-b263-4edc-93f6-43bbc57f5cf7.png)

To add a custom 404 page like the one above, I installed the [sphinx-notfound-page](https://github.com/readthedocs/sphinx-notfound-page) extension, added it to my [`_config.yml`](https://github.com/melaniewalsh/Intro-Cultural-Analytics/blob/master/book/_config.yml) file as an extra extension, and [configured it like so](https://github.com/melaniewalsh/Intro-Cultural-Analytics/blob/master/book/_config.yml#L70-L83):

```
sphinx:
  extra_extensions:
    - notfound.extension
  config:
    notfound_context:
        body: "<h1>Whoops! Page Not Found</h1>\n\n<p>Sorry, this page doesn't exist. Many sections of this book have been updated recently.</p><p>Try the <a href='https://melaniewalsh.github.io/Intro-Cultural-Analytics/index.html'>home page 🏠 </a> or <a href='https://melaniewalsh.github.io/Intro-Cultural-Analytics/search.html'>search page 🔎 </a> to find what you're looking for.</p>"
    notfound_urls_prefix: "/Intro-Cultural-Analytics/"
```
The configuration step that finally made the extension work for me was setting [`notfound_urls_prefix`](https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html#confval-notfound_urls_prefix) to the name of my repository.
