### DISCUSSION TITLE
Environment variable to Jupyter Notebook

### DISCUSSION THREAD

**Discussion by JosephTLucas** [executablebooks/meta#557] [Q&A] [answered]
In a notebook, I want to call `key = os.getenv("API_KEY")`. I modified the build yml:
```
    - name: Build the book
      env: 
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        jupyter-book build .
```

but the notebook still doesn't seem to be able to access the key. Any thoughts? (The API key is stored in the gh secrets section of the repo)
