### DISCUSSION TITLE
How can I reference a relative directory in _toc.yml

### DISCUSSION THREAD

**Discussion by canyon289** [executablebooks/meta#580] [Q&A]
Hi, 
I'm having trouble getting jupyter book to find my notebook files. I would like to structure my jupyter book as follows

```
toplevel/
  - jp_book_config/
    - _config.yml
    - _toc.yml
  - notebooks
    - chp_01.ipynb
    - chp_02.ipynb
```

What's the correct way to reference the notebook files? Here's my current _toc.yml. I run `jb build jupyter_book/`from the toplevel directory but I get a not found error from toctree.
```
format: jb-book
root: index
chapters:
  - file: ../notebooks/chp_01.ipynb
  - file: ../notebooks/chp_02.ipynb
```

What should I set for the filepath string?

And thanks for creating jupyterbook, its quite a nice library!

Here's the versions
```
Jupyter Book      : 0.12.1
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.1
Sphinx Book Theme : 0.1.7
Jupyter-Cache     : 0.4.3
```

![image](https://user-images.githubusercontent.com/7213793/146647959-fce6766d-068b-440f-a448-973cfedb1e3e.png)
