### DISCUSSION TITLE
Coloring jupyter book text properly

### DISCUSSION THREAD

**Discussion by mscharling** [executablebooks/meta#588] [Q&A] [answered]
Hi,

I'm very new to all this kinda stuff and I've been digging a lot to find something about how one changes the text coloring in the standard jupyter theme (Sphinx Book Theme, I know). I haven't tried making custom css before, so I was hoping someone could explain to me how I change the blue color when hovering the text in the sidebar to some other color. 

Is there some primary color which can be changed? I guess I would like to change all places with the blue colored text to some other color.

I hope my question i somewhat clear😅

**Comment by ZviBaratz** [comment, marked as answer]
Hi @mscharling,
Generally speaking, to add custom CSS follow [the docs](https://jupyterbook.org/advanced/html.html#custom-css-or-javascript) and create `book/_static/custom.css`. 
More specifically, links are represented by HTML's [`<a>`](https://www.w3schools.com/tags/tag_a.asp) tag. To change the color of hovered links, you should include the following rule in your CSS:

```css
a:hover {
    color: red;
}
```

Jupyter book adds the `"reference"` and `"internal"` classes to the table of content links, so if you wanted to change only those, it would be:

```css
a.reference.internal:hover {
    color: red;
}
```

However, it seems like this rule is overridden by the theme, so to force it you should include the [`!important`](https://www.w3schools.com/css/css_important.asp) tag:

```css
a.reference.internal:hover {
    color: red!important;
}
```

Hope this helps!
