### DISCUSSION TITLE
Custom `tableofcontents` directive maxdepth setting

### DISCUSSION THREAD

**Discussion by ZviBaratz** [executablebooks/meta#592] [Q&A]
Hi all :wave: 

I am trying to create a book formatted as a PhD thesis. My current toc structure is:
```
# Table of contents
format: jb-book
root: front
chapters:
# - file: acknowledgements
- file: abstract
- file: content
  options:
    numbered: true
  sections:
  - file: chapters/introduction
  - file: chapters/goals
  - file: chapters/methods
  - file: chapters/results
  - file: chapters/discussion
  - file: chapters/bibliography
```

and `content.md` contains:

````
# Contents

```{tableofcontents}
```
````

I would like to be able to set the `maxdepth` of the displayed table of contents, but can't seem to find any way to access it. 
Any help resolving this would be greatly appreciated.
Thank you so much for all your great work!

**Comment by choldgraf** [comment]
cc @AakashGfude - do you know if it's possible to pass the other Sphinx `toctree` directive options to the `tableofcontents` directive, so that things like depth can be controlled?

**Reply by ZviBaratz** [reply]
Also, is there any way to combine both `chapters` and `parts` in a single toc tree (i.e. to replace `content` in the given example with a nested `parts` section)?

**Comment by chrisjsewell** [comment]
Yep, if I remember correctly, you just add it in your `_toc.yml`:

```yaml
# Table of contents
format: jb-book
root: front
chapters:
# - file: acknowledgements
- file: abstract
- file: content
  options:
    numbered: true
    maxdepth: 2
  sections:
```

then `tableofcontents` is just setting a "placeholder" of where to put the generated `toctree` (rather than hiding it).

Note, the full implmentation is in: https://github.com/executablebooks/sphinx-external-toc

**Reply by ZviBaratz** [reply]
Hi @chrisjsewell, thank you for your comment. Unfortunately, I did try that, but the tree is still rendered with one level. Should I open an issue?

My `_toc.yml` file is:

```yml
# Table of contents
format: jb-book
root: front
chapters:
# - file: acknowledgements
- file: abstract
- file: content
  options:
    numbered: true
    maxdepth: 4
  sections:
  - file: lists
  - file: chapters/introduction
  - file: chapters/goals
  - file: chapters/methods
  - file: chapters/results
  - file: chapters/discussion
  - file: chapters/bibliography
```

`content.md` is:

````
# Contents

<hr>

```{tableofcontents}
```
````

and the result is:

![image](https://user-images.githubusercontent.com/22370149/147737000-c322892b-17c6-4408-8994-ef1820dde6c5.png)
