### DISCUSSION TITLE
Jupyterbook TOC parts renumbering

### DISCUSSION THREAD

**Discussion by chipbrock** [executablebooks/meta#605] [Q&A]
As I understand it, when one specifies parts in the _toc.yml file, then renumbering of chapters happens at each part. Is there any way to disable that feature? I'd like for chapter numbering to continue ordinally, using parts as just a benign separator among the chapters.

What I have is:

```
# Table of content
# Learn more at https://jupyterbook.org/customize/toc.html
#
format: jb-book
root: intro
options:
  numbered: True
chapters:
- file: FOUNDATION
parts:
  - caption: Foundations
    numbered: True
    chapters:
    - file: e_and_m/J-140_Maxwell_3_S0
      sections:
      - file: e_and_m/J-140_Maxwell_3_S1
      - file: e_and_m/J-140_Maxwell_3_S2
      - file: e_and_m/J-140_Maxwell_3_S3
      - file: e_and_m/J-140_Maxwell_3_S9
      - file: e_and_m/J-140_Maxwell_3_S11

  - caption: Relativity
    numbered: True
    chapters:
    - file: relativity/Special Relativity_1_1_VSC
    - file: relativity/Special Relativity_2_1
    - file: relativity/Special Relativity_3_1
    - file: relativity/Special Relativity_4_1

```

So, _J-140_Maxwell_3_S_0_ is chapter 1 and _Special Relativity_1_1_VSC_ is also chapter 1.

I could accomplish the same thing I guess, if I could include new chapters called Foundations.md and Relativity.md but exclude them from numbering. Can I do that?

thanks
