### DISCUSSION TITLE
Executing Rmarkdown in jupyter-book

### DISCUSSION THREAD

**Discussion by ozika** [executablebooks/meta#627] [Q&A]
Hi all,  

I would like to build a book that's made mostly of python notebooks + one/two notebooks in Rmarkdown.  
I came across about [this bit on the docs](https://jupyterbook.org/file-types/jupytext.html) about telling sphinx how to deal with `Rmd`, however, this doesn't actually run the cells. It treats the document as a `md` file with code blocks.  

It might be a stretch, but is there a way to execute `Rmd` when building? Alternatively, could one run `Rmd` in RStudio and then add the generated `html` file? 

Thanks! Ondrej

**Comment by chrisjsewell** [comment]
> however, this doesn't actually run the cells

Heya, yep it does execute the cells: the page you point to is an rmd that has been read and executed by jupyter-book. Perhaps your configuration is incorrect for execution

**Reply by ozika** [reply]
mh, what *could* be wrong then? do you have any working examples of this? I have tried quite a few things and nothing seems to work

**Reply by ozika** [reply]
maybe a better question would be - what is *required* for it to run. I have `jupyter-book` and `jupytext` on the most recent versions. I am not telling `jupyter-book` anything about what `R` kernel to use for example.

**Reply by chrisjsewell** [reply]
Well the juyter-book documentation itself is the working example, e.g. you can see it being read/executed in the CI here: https://github.com/executablebooks/jupyter-book/runs/4755786872?check_suite_focus=true

![image](https://user-images.githubusercontent.com/2997570/148822144-9cca1235-98ad-46d1-83b9-008d9a99fd79.png)

**Reply by chrisjsewell** [reply]
Is anything in your book executing, e.g. do you have a standard .ipynb notebook in there that correctly executes, and have you changed anything on the execution configuration: https://jupyterbook.org/content/execute.html#trigger-notebook-execution

**Reply by chrisjsewell** [reply]
what is the contents of your `_config.yml`?

**Reply by ozika** [reply]
Yes, there are a bunch of `.ipynb` ntbks that run fine. Here is the `_config.yml` file: 

```
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Longitudinal study on worries and COVID
author: Ondrej Zika

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/ozika/covid_public  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

sphinx:
  config:
    nb_custom_formats:
        .Rmd:
            - jupytext.reads
            - fmt: Rmd

html:
  use_issues_button: true
  use_repository_button: true

```
