### DISCUSSION TITLE
Yaml reader for sphinx - based on MyST?

### DISCUSSION THREAD

**Discussion by arwedus** [executablebooks/meta#638] [Q&A]
Hi @chrisjsewell,

I was looking for a YAML reader that parses yaml into Sphinx directives, e.g. directly from yaml files. As MyST already supports a little bit of yaml syntax, I was wondering if you just use parts of a larger yaml parser and could do more, or if you're just supporting that particular bit of yaml syntax?

What I'm talking about is the directives option, like:

````
```{directive} title
---
option1: value
option2: value
---
Content
```
````

**Comment by chrisjsewell** [comment]
Heya, I'm not quite sure what you after? As in reading directives options from a YAML file, like

`my_options.yaml`:
```
option1: value
option2: value
```

````markdown
```{directive} title
options: my_options.yaml

Content
```
````

**Reply by arwedus** [reply]
Actually, I'm looking to parse simple yaml files as input to Sphinx, e.g.

```yaml
--- # data.yaml
- directive1
  title: The title
  option1: this
  option2: that
  content: |
    here I can put random RestructuredText but no `directives <https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#directives>`_

- note
  title: this is a standard rST directive
  content: |
    I'm **bold**.
```

This would probably be another extension. I just wanted to know if the basis of this is already available in MyST and could be easily re-used.
