### DISCUSSION TITLE
Use executed code in a previous file

### DISCUSSION THREAD

**Discussion by yangli-stat** [executablebooks/meta#656] [Q&A]
One of my chapters (chapter 2) has several sections. They are saved in separate files. The _toc.yml file looks like this.

```
format: jb-book
root: intro
options:
  numbered: true
chapters:
- file: chapter1/chap1.ipynb
- file: chapter2/chap2main.ipynb
  sections:
  - file: chapter2/chap2sec1.ipynb
  - file: chapter2/chap2sec2.ipynb
  - file: chapter2/chap2sec3.ipynb
  - file: chapter2/chap2sec4.ipynb
```

In chap2sec1.ipynb, there is a command `import pandas as pd` to load pandas. All codes with `pd.read_csv` in this section work fine. 

In chap2sec2.ipynb, I am trying to read another file using `mydata = pd.read_csv("...")`. Something is wrong because there is an error message in the book.

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/var/folders/tq/mrh1ffvs7jqbpmh3f2w5qf3c0000gn/T/ipykernel_43122/2091571339.py in <module>
----> 1 mydata = pd.read_csv("...")

NameError: name 'pd' is not defined
```

It seems the command executed in an earlier file doesn't follow through to subsequent files. How do I fix this? Thanks.
