### DISCUSSION TITLE
github actions build fails when trying to conda activate environment

### DISCUSSION THREAD

**Discussion by joemcglinchy** [executablebooks/meta#686] [General] [answered]
Hi all,

Thank you for contributing to this awesome project! My team is hopeful to get this up and running for some of our product documentation and walkthroughs.

I looked through the discussion topics and was unable to find much relevant (found https://github.com/executablebooks/meta/discussions/315), so I wanted to start this thread.

I am running jupyter-book on my WSL2 Ubuntu, with the following:
jupyter-book              0.12.2
python                    3.9.6

and have successfully (LOCAL only) built a jupyter book with MD files as well as .ipynb files which use a different conda environment. I'm trying to deploy this now through github pages and running into errors trying to create and activate this environment. Has anyone successfully deployed to github pages specifying a conda environment for the notebooks that isn't `base`? 

Contents of my deploy.yml file, which has calls to create the ipython kernel which matches what I have in my notebooks:
 ```
name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: hy_environment.yml
        activate-environment: wsl_hydro
        python-version: 3.7
        auto-activate-base: false
    
    - name: activate wsl_hydro
      run: |
       $CONDA/bin/conda init bash
       source ~/.bashrc
       $CONDA/bin/conda activate wsl_hydro
       $CONDA/bin/conda install -c conda-forge -n wsl_hydro ipykernel -y
       ipython kernel install --user --name=wsl_hydro --display="python3 (wsl_hydro)"
       pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
```

errors on the build:
![image](https://user-images.githubusercontent.com/4762214/156462864-e8eacb71-1ca9-40ac-98f3-7c6aee678474.png)

I have tried separating out the terminal calls under `activate wsl_hydro` into their own sections, but am getting hung up on trying to activate the environment and make it accessible to the (remote) jupyter book build.

Is configuring a conda environment other than `base` environment possible in this context?

thank you!!
-Joe
