### DISCUSSION TITLE
RTD theme, titlesonly for second-level subtree

### DISCUSSION THREAD

**Discussion by mikemckiernan** [executablebooks/meta#716] [Show and tell]
I was optimistic that I could show first-level headings in some files (I believe that `maxdepth: 1` will cover that), but use `subtrees:` like the foll example from the repository:

```yaml
root: intro
subtrees:
- caption: User Guide
  numbered: true
  entries:
  - file: user_guide/sphinx
  - file: user_guide/cli
  - file: user_guide/api
- caption: Example
  entries:
  - file: example/index
    subtrees:
    - titlesonly: True
      entries:
      - file: example/subfolder/page
      - glob: example/globfolder/*
- caption: Links
  entries:
  - title: GitHub Repository
    url: https://github.com/executablebooks/sphinx-external-toc
```

It seems valid, but I didn't expect "First second-level heading" or "Second second-level heading" to be included in the TOC.

![image](https://user-images.githubusercontent.com/18604620/162578809-1022237c-e3d0-4b67-96eb-2f270cb59bd1.png)

You can peek at the modifications that made at https://github.com/mikemckiernan/sphinx-external-toc/pull/1/files.

Is it intentional that the second-level headings appear?  My interest is to prevent them from appearing.
