### DISCUSSION TITLE
how do I include a .tex macros file inside every ipynb file/ chapter?

### DISCUSSION THREAD

**Discussion by murphyk** [executablebooks/meta#739] [Q&A] [answered]
Hi

I am able to define latex math macros in each notebook separately by writing things like
```
```{math}

\newcommand{\real}{\mathbb{R}}
...
```
But I don't want to repeat this in each file.

I would like to import an existing .tex file with macro definitions.
It seems that [jupyter contrib nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1257) supports this, but I don't know how to make this work with jupyter book. Any advice?

PS. I've tried to define some common macros to my `_config.yml` file following the [official document](https://jupyterbook.org/en/stable/advanced/sphinx.html?highlight=include%20tex%20macros#defining-tex-macros)
but it does not work. For exmaple, suppose I add
```
sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
```
and then put this in my .ipynb file:
```
Here is $\N=10$ and blah. $\floor{42.3}= 42$.
```
generates this:
<img width="388" alt="Screen Shot 2022-05-13 at 4 08 42 PM" src="https://user-images.githubusercontent.com/4632336/168399975-243efb6c-9221-4941-aec2-e2298599a2e4.png">

**Comment by mmcky** [comment, marked as answer]
Thanks @murphyk. 

This has recently been updated in the docs but it is currently only reflected in the `latest` version and not reflected on `stable` yet.

https://jupyterbook.org/en/latest/advanced/sphinx.html (tag: latest bottom right)

`mathjax v3` has updated some internal tag definitions so the `TeX` and `Macros` should all be lower case in the `_config.yml`

```yaml
sphinx:
  config:
    mathjax_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
```

Would you mind giving that a try to see if that fixes your issue?

P.S. `Machine Learning: A Probabilistic Perspective` is a core member of my `machine learning` book library -- a beautiful book ❤️
