### DISCUSSION TITLE
Sectioning is not working for a certain notebook

### DISCUSSION THREAD

**Discussion by rclUPC** [executablebooks/meta#749] [Q&A] [answered]
Hi, 
I am creating an educational book with Jupyter Notebooks for Fluid Mechanics. You can check it [here](https://rclupc.github.io/AdvancedFluidMechanics/README.html).
As you can see, there are (or ther should be) 6 sections, according to the [toc file](https://github.com/rclUPC/AdvancedFluidMechanics/blob/main/_toc.yml):
```
format: jb-book
root: README
chapters:
- file: 0-Intro/IntroPython
  sections:
  - file: 0-Intro/Assignment0
- file: 1-microFlows/Microflows
  sections:
  - file: 1-microFlows/Assignment1
- file: 2-Rheology/rheology
  sections:
  - file: 2-Rheology/FDMViscoelastic
  - file: 2-Rheology/Assignment2
- file: 3-Turbulence/turbulence
  sections:
  - file: 3-Turbulence/ExperimentalMeasurements
  - file: 3-Turbulence/Assignment3
- file: 4-BoundaryLayer/BoundaryLayer
  sections:
  - file: 4-BoundaryLayer/Assignment4
- file: 5-CompressibleFlow/CompressibleFlow
  sections:
  - file: 5-CompressibleFlow/Assignment5
```
But the section 2 is not being sectioned.

![image](https://user-images.githubusercontent.com/26278027/170819236-772d5b57-7929-470d-9366-6e98f1849435.png)

I have no idea what is wrong with this Notebook. I don't know if it a bug, or there is something I am doing wrong.
Hope anyone can see the issue.
Kind regards
Robert
