### DISCUSSION TITLE
Adding artifact upload for generated build reports in cookiecutter template

### DISCUSSION THREAD

**Discussion by ZviBaratz** [executablebooks/meta#794] [Ideas]
Hi everyone,

I recently had some relatively challenging build errors that could not be reproduced locally and ended up adding the following step to my GitHub actions workflow configuration file:
```yml
      ...
      - name: Upload build reports if created
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: src/book/_build/html/reports
          if-no-files-found: ignore
      ...
```
Seems to me this would generally make for a useful step to have, so I wanted to propose coming up with a PR to update the [cookiecutter template](https://github.com/executablebooks/cookiecutter-jupyter-book) and [docs](https://jupyterbook.org/en/stable/publish/gh-pages.html). I was wondering whether that would make a welcome contribution, any thoughts would be appreciated. 

Thank you!
Zvi
