### DISCUSSION TITLE
Jupyter-Book vs a private Gitlab instance

### DISCUSSION THREAD

**Discussion by tschm** [executablebooks/meta#819] [Q&A]
All our code is in various repos that are all hosted on self-managed Gitlab servers. Jupyter-Book works great --- thank you Team!

However, I can't get the Launch Buttons to work. We have started to use a JupyterHub server I want to use. Needless to say that I can't use public services such as Binder. A typical _config.yml file looks like this:

```
➜  book git:(main) ✗ cat _config.yml
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ...
author: ...
logo: static/logo.png
only_build_toc_files: true

execute:
  execute_notebooks: force
  timeout: 240

launch_buttons:
  notebook_interface: "jupyterlab" 
  jupyterhub_url: "https://..."

# Information about where the book exists on the web
repository:
  url: https://...  # Online location of your book. Repo on a private Gitlab server
  path_to_book: book  
  branch: main  

html:
  use_issues_button: true
  use_repository_button: true
```
