### DISCUSSION TITLE
Creating a Cover Page for JupyterBook latex pdf

### DISCUSSION THREAD

**Discussion by Radhika677** [executablebooks/meta#977] [Q&A]
I wish to develop a stylesheet (cover page) for my latex document with a Title (colour Dark Green) and Author names (colour golden) and background colour as Green. I'm developing this in JupyterBook and building it by the following command:
```bash
Jupyter-book build bookname --/builder pdflatex.
```
Following is my `_config.yml` file:
```yaml
title: /color{black!60!Green!70!blue} Digital Services
author: Radhika Saraf
logo: logo.png
```
Can anybody please help me to write the jupyterbook configuration to get colours for author name and a background colour/background image?

Could you please help me with this? I'll be really grateful.
Thanks!
