### DISCUSSION TITLE
Inline math delimiters

### DISCUSSION THREAD

**Discussion by kalvotom** [executablebooks/meta#982] [Q&A]
Hi!

Is it possible to configure the book build system in such a way that math expressions delimited both by `$ ... $` and `\( ... \)` are parsed?

I have searched the documentation and it seems to me that it is possible to choose only one of these options (by toggling the `dollarmath` extension).

Thanks in advance for any answer or idea!

Tomáš

**Comment by kalvotom** [comment]
OK, it looks like I have succeeded. `sphinx` and `parse` parts of my `_config.yml` look like this:

```
parse:
  myst_update_mathjax: false
  myst_enable_extensions:
    - amsmath
    - dollarmath

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        inlineMath: [['$', '$'], ['\(', '\)']]
```

Then it took me quite a while to realize that `parse` portion of the config accepts only three (?) `myst_*` options! At least that is how I understand [this line in the source code](https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/config.py#L344). So, adding `myst_update_mathjax` to the list on that line fixed my problem...

Is this really the desired behaviour? It seems to me that the build script simply ignores most of [myst options](https://myst-parser.readthedocs.io/en/latest/configuration.html). Or am I misinterpreting something?
