### ISSUE TITLE
Some gallery images are not displaying

### ISSUE THREAD

**Issue by mikofski** [executablebooks/meta#395]
**Describe the bug**

The gallery page: https://executablebooks.org/en/latest/gallery.html has some images that don't show

[UPDATE] the default image: https://jupyterbook.org/_static/logo.png returns 404
![image](https://user-images.githubusercontent.com/1385621/121566992-ebb8bd00-c9d2-11eb-8b33-33d964af9834.png)

I think the name has changed and it should be https://github.com/executablebooks/meta/blob/master/docs/_static/logo-square.png ?

![logo-square](https://raw.githubusercontent.com/executablebooks/meta/master/docs/_static/logo-square.png)

**To Reproduce**

1. Go to https://executablebooks.org/en/latest/gallery.html'
3. Scroll down to "stats and data science" or "Markov Chains" or "genome sampler" ...
4. do not see image:
![image](https://user-images.githubusercontent.com/1385621/121564792-b1e6b700-c9d0-11eb-895f-5f07fed76380.png)

Also related: if an image is from a GitHub repo, and not linked to its raw location, then it will also not show up - perhaps this should be in a yaml comment at the top of the `gallery.yml` file to help/guide contributors?

**Expected behavior**

1. images that are not currently showing up are either removed of improved.
    * I think it's okay for anyone to do this as long as they @ the contributor of the original PR, or
    * perhaps it's better for the original contributors to make a new PR with the fix, or 
    * perhaps when the PRs are merged they should be screened for this or 
    * perhaps they were but since then the image location has changed and now it's a 404?

2. add comments to help contributors add new gallery links, and that if link is GH repo, use raw link

3. if `image` field is blank or missing, show generic image
    * I think possibly it the gallery is already trying to do this, but he generic image is broken?

https://executablebooks.org/en/latest/gallery.html

### minimal example

```yaml
# please add name, website, repo, & image to list
# if using GH, please add raw link to image
# if no image, omit field
# check image before merging PR
# if any links become stale, please update or after a deprecation period of 1yr, the links will be removed
# your links may be updated for maintenance, jb-maintainers will attempt to contact you via GH 
- name: genome-sampler Software Documentation
  website: https://caporasolab.us/genome-sampler/
  repository: https://github.com/caporaso-lab/genome-sampler
  image:
- name: Continuous Time Markov Chains
  website: https://jstac.github.io/continuous_time_mcs/intro.html
  repository: http://github.com/jstac/continuous_time_mcs
- name: Statistics and Data Science
  website: https://cranmer.github.io/stats-ds-book/intro.html
  repository: https://github.com/cranmer/stats-ds-book
  image:
```
