### ISSUE TITLE
Specify a minimum amount of codecov coverage for PR success

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#87]
We are using codecov across a few repositories for our coverage. However we don't have any official practice around using it. Should we agree upon a convention for "how much new additions need to be covered for a PR to pass"? And if so, can we document how to set this per repository?

**Comment by chrisjsewell** [comment]
FYI you can use https://docs.codecov.io/docs/codecovyml-reference,
e.g. I added one to https://github.com/executablebooks/sphinx-tabs/blob/master/codecov.yml

**Comment by chrisjsewell** [comment]
Coverage % is obviously a bit subjective, but ideally I guess > 90% is ideal and 80% ok 
currently:

markdown-ipy: 95%
myst-parser: 91%
myst-nb: 85%
jupyter-cache: 81%
jupyter-book: 82%
...

**Comment by chrisjsewell** [comment]
In myst-parser, I have now added:

```yaml
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
    patch:
      default:
        target: 85%
        threshold: 0.5%
```
